### ISSUE TITLE
safe mint reverts

### ISSUE THREAD

**Issue by stevennevins** [z0r0z/Helios#11]
Pretty sure there is an issue with the _mint revert conditions, and the safeTransfer and batch methods probably have the same problem.  I converted the [repo to foundry](https://github.com/stevennevins/Helios) and had an issue minting to an EOA (which didn't seem to be an issue when I initially ran the test as a hardhat repo).  Converting the if/revert condition to the require statement from solmate made the method work as expected.

**Comment by z0r0z** [comment]
great catch @stevennevins I have fixed this issue, as the safety checks were not proper in _mint
