### ISSUE TITLE
potentially unsafe multicall

### ISSUE THREAD

**Issue by stevennevins** [z0r0z/Helios#13]
linking this [discussion](https://github.com/Uniswap/v3-periphery/issues/52) on use of msg.value in payable functions and multicall

**Comment by z0r0z** [comment]
thanks @stevennevins This seems like a good fix. The only benefit of having multi-call payable is gas-optimization by avoiding redundant check in solidity. Will remove payable keyword as it's not worth it, and this contract will hold LP ETH.
