### ISSUE TITLE
Typescript support for hardhat vs foundry

### ISSUE THREAD

**Issue by shortdoom** [z0r0z/Helios#18]
I just noticed that there was a [discussion](https://github.com/z0r0z/Helios/issues/4#issuecomment-1054266635) about transferring repository into foundry from hardhat.

At the same time, I've also translated template from vanilla JS to typescript support (helps in scripting). Here is my fork, I re-wrote all of the test and created few quick helper functions https://github.com/shortdoom/Helios

I do plan to tackle some Issues so it would be nice to decide for a template. Vanilla JS hardhat definitely makes least sense.

I also use foundry and it beats hardhat in speed and ease of testing but at the same time has pretty poor support for scripting and more advanced ops involving local network. It's possible that addon of hardhat/vanilla JS *inside* of foundry template would be necessary at some point anyways.

**Comment by bayological** [comment]
@shortdoom IMO foundry makes more sense. I played around with it and didn't have any issues writing normal tests, you can also do fuzz testing without any additional dependencies. Also it feels better writing the tests in the same language. Would be interesting to know more about the poor support for advanced local network ops though.

**Comment by z0r0z** [comment]
thanks for feedback @bayological Looks like initial consensus from peanut gallery is pointing at foundry, per andy, `Testing speed is v op`
