### ISSUE TITLE
Conflicting Operations

### ISSUE THREAD

**Issue by denizmatar** [z0r0z/Helios#5]
Hello,

In [Helios](https://github.com/z0r0z/Helios/blob/main/contracts/Helios.sol) line 103, `token0` is assigned to the BIGGER one. But in line 106, `token0` is assigned to the SMALLER one. Token amounts are also assigned accordingly.

Also, having two similar comments on the lines 96 and 98 made me think that there was a problem in this part, and the old and new version were mixed. If this is true, and this is the latest stable version, I recommend removing between lines 97-105.

**Comment by nemani** [comment]
Will send a PR removing lines 106 & 107.
